# Generated by Django 3.2.7 on 2021-09-23 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(default='2021-06-20')),
                ('type', models.CharField(choices=[('Poule pondeuse', 'Poule pondeuse'), ('Poulet de chair', 'Poulet de chair')], default='Poule pondeuse', max_length=17)),
                ('etat', models.CharField(choices=[('Inachevé', 'Inachevé'), ('Achevé', 'Achevé')], default='Inachevé', max_length=9)),
                ('nb_poulet', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Poulette', 'Poulette'), ('Pondeuse I', 'Pondeuse I'), ('Pondeuse II', 'Pondeuse II'), ('Pondeuse III', 'Pondeuse II')], default='Poulette', max_length=17)),
                ('quantité', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=20)),
                ('date_prescrit', models.DateField(default='2021-06-20')),
                ('description', models.CharField(blank=True, default='description not available', max_length=100)),
                ('prix_unitaire', models.CharField(blank=True, default='000', max_length=20)),
                ('prix_total', models.IntegerField(default=0)),
                ('etat', models.CharField(choices=[('Inachevé', 'Inachevé'), ('Achevé', 'Achevé')], default='Inachevé', max_length=9)),
                ('elevage', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='elevageAPI.elevage')),
            ],
        ),
        migrations.CreateModel(
            name='Prevaccin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=100)),
                ('description', models.CharField(blank=True, default='description not available', max_length=300)),
                ('date_debut', models.DateField(default='2021-06-20')),
                ('date_fin', models.DateField(default='2021-06-20')),
                ('prix_unitaire', models.IntegerField(default=0)),
                ('prix_total', models.IntegerField(default=0)),
                ('etat', models.CharField(choices=[('Inachevé', 'Inachevé'), ('Achevé', 'Achevé')], default='Inachevé', max_length=9)),
                ('elevage', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='elevageAPI.elevage')),
            ],
        ),
        migrations.CreateModel(
            name='Nourriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Poulette', max_length=200)),
                ('date_debut', models.DateField(default='2021-06-20')),
                ('date_fin', models.DateField(default='2021-06-20')),
                ('quantité_journalière', models.IntegerField(default=0)),
                ('total_journalière', models.IntegerField(default=0)),
                ('quantité_total', models.IntegerField(default=0)),
                ('etat', models.CharField(choices=[('En cours', 'En cours'), ('Terminé', 'Terminé')], default='En cours', max_length=9)),
                ('details', models.CharField(blank=True, default='Aucune informations', max_length=200)),
                ('prix', models.IntegerField(default=0)),
                ('poids_estimé', models.IntegerField(default=0)),
                ('poids_prelevé', models.IntegerField(default=0)),
                ('observation', models.CharField(choices=[('NaN', 'NaN'), ('Anormal', 'Anormal'), ('Normal', 'Normal'), ('Excellent', 'Excellent')], default='NaN', max_length=15)),
                ('elevage', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='elevageAPI.elevage')),
            ],
        ),
        migrations.CreateModel(
            name='Eau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(default='2021-06-20')),
                ('date_fin', models.DateField(default='2021-06-20')),
                ('quantité_journalière', models.IntegerField(default=0)),
                ('total_journalière', models.IntegerField(default=0)),
                ('quantité_total', models.IntegerField(default=0)),
                ('etat', models.CharField(choices=[('En cours', 'En cours'), ('Terminé', 'Terminé')], default='En cours', max_length=9)),
                ('prix', models.IntegerField(default=0)),
                ('elevage', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='elevageAPI.elevage')),
            ],
        ),
    ]
