# Generated by Django 3.2.5 on 2021-08-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevageAPI', '0002_auto_20210818_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevage',
            name='type',
            field=models.CharField(choices=[('Poule pondeuse', 'Poule pondeuse'), ('Poulet de chair', 'Poulet de chair')], default='Poule pondeuse', max_length=17),
        ),
        migrations.AddField(
            model_name='nourriture',
            name='nom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='elevage',
            name='etat',
            field=models.CharField(choices=[('Inachevé', 'Inachevé'), ('Achevé', 'Achevé')], default='Inachevé', max_length=9),
        ),
        migrations.AlterField(
            model_name='nourriture',
            name='prix',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nourriture',
            name='quantité_journalière',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nourriture',
            name='quantité_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nourriture',
            name='total_journalière',
            field=models.IntegerField(default=0),
        ),
    ]
