# Generated by Django 3.2.5 on 2021-08-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevageAPI', '0003_auto_20210825_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nourriture',
            name='nom',
            field=models.CharField(default='Poulette', max_length=100),
        ),
    ]
