# Generated by Django 3.2.5 on 2021-09-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevageAPI', '0004_alter_nourriture_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Poulette', 'Poulette'), ('Pondeuse I', 'Pondeuse I'), ('Pondeuse II', 'Pondeuse II'), ('Pondeuse III', 'Pondeuse II')], default='Poulette', max_length=17)),
                ('quantité', models.IntegerField(default=0)),
            ],
        ),
    ]
